### PR TITLE
Solving issue #35

### PR DESCRIPTION
**Pull request by LuisLauM**
Solving issue #35 applying the solution https://github.com/paleolimbot/rbbt/issues/35#issuecomment-1547770626

### CODE REVIEW

**Comment by dmi3kno** [comment]
I suggest we do it via options(), so that users would be able to adjust it. I am pushing a PR in few minutes. Let's take these two issues separately (in two different PRs)

**Comment by bwiernik** [comment]
@paleolimbot Can you add me as a collaborator again so I can merge this commit?

**Comment by bwiernik** [comment]
@paleolimbot Sorry, apparently my internet connection wasn't working when I accepted the invitation and it didn't go through. Could you resend the collaboration invite? I've got the bugs in this PR all fixed.

**Comment by dmi3kno** [comment]
If you decide to merge this instead of #42 could you, please add more prefixes, other than just `^fig-` and `^tbl-`? I would ideally want a pair of eyes to look at my alternative implementation and critique it (#42).

**Comment by bwiernik** [comment]
@paleolimbot just bumping this

**Comment by LuisLauM** [comment]
> @paleolimbot just bumping this

Oh, I am sorry. I did not realize that the changes on my fork will be taking into account here. I have just using the original code of @paleolimbot but introducing some features that works for me. Again, my apologizes, I will remove this thread.

**Pull request closed without merging**
